### ISSUE TITLE
community.docker 3.0.0-a2 is unavailable for installation

### ISSUE THREAD

**Issue by EldarKurbanov** [ansible-community/molecule-docker#161]
Dear molecule-docker developers! 
I hope you are well-doing. Your product is great and gave me good experience with ansible playbooks testing. Really appreciate your work.

Could you help me with one issue? 

I met one problem with new release on my local machine. Also, I met it inside `ubuntu:latest` fresh Docker container with ansible installed.
```
molecule test
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun with role_name_check=0...
INFO     Set ANSIBLE_LIBRARY=/home/eldar/.cache/ansible-compat/cae662/modules:/home/eldar/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Set ANSIBLE_COLLECTIONS_PATH=/home/eldar/.cache/ansible-compat/cae662/collections:/home/eldar/.ansible/collections:/usr/share/ansible/collections
INFO     Set ANSIBLE_ROLES_PATH=/home/eldar/.cache/ansible-compat/cae662/roles:/home/eldar/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO     Using /home/eldar/.cache/ansible-compat/cae662/roles/chainhog.base symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Running default > dependency
INFO     Running ansible-galaxy collection install -v community.docker:>=3.0.0-a2
WARNING  Retrying execution failure 1 of: ansible-galaxy collection install -v community.docker:>=3.0.0-a2
ERROR    Command returned 1 code:
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map

ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* community.docker:>=3.0.0-a2 (direct request)

Traceback (most recent call last):
  File "/home/eldar/.local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/command/test.py", line 176, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/command/base.py", line 121, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/command/base.py", line 165, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/command/base.py", line 154, in execute_subcommand
    return command(config).execute(args)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/command/dependency.py", line 74, in execute
    self._config.dependency.execute()
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/dependency/ansible_galaxy/__init__.py", line 76, in execute
    invoker.execute()
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/dependency/ansible_galaxy/base.py", line 120, in execute
    super().execute()
  File "/home/eldar/.local/lib/python3.10/site-packages/molecule/dependency/base.py", line 92, in execute
    self._config.runtime.require_collection(name, version)
  File "/home/eldar/.local/lib/python3.10/site-packages/ansible_compat/runtime.py", line 398, in require_collection
    self.install_collection(f"{name}:>={version}")
  File "/home/eldar/.local/lib/python3.10/site-packages/ansible_compat/runtime.py", line 222, in install_collection
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Command returned 1 code:
No config file found; using defaults
Starting galaxy collection install process
Process install dependency map

ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* community.docker:>=3.0.0-a2 (direct request)

make: *** [Makefile:30: e2e-test] Ошибка 1
```

I tried to install ansible collection "community.docker" manually:
```
[eldar@homepcfedora tasks]$ ansible-galaxy collection install community.docker --upgrade
Starting galaxy collection install process
Process install dependency map
Starting collection install process
'community.docker:2.7.0' is already installed, skipping.
```
But it looks like my ansible-galaxy don't see new version of "community.docker" package. 

My "/etc/ansible" file is empty. 
My "ansible.cfg" contains it:
```
[default]
host_key_checkign	=	false
inventory = ./inventory/hosts
```  
So, I don't use any custom ansible galaxy server.

Thank you in advance for the help.

Kind regards,
Eldar Kurbanov

**Comment by hylaride** [comment]
I ran into this.  You need to manually install it with ansible-galaxy collections
```
ansible-galaxy collection install community.docker:=3.0.0-a2
```

**Comment by ssbarnea** [comment]
You failed to include output of `molecule --version`, somehow I suspect you might not use the latest version. Also a `pip freeze|grep ansible` could help here.

**Comment by mkroman** [comment]
Currently experiencing the same issue on Arch Linux.

Versions for `molecule` and `molecule-docker` packages:

```
% pacman -Qi molecule molecule-docker | awk '/^Name/ { name = $3 } /^Version/ { print name, $3 }'
molecule 4.0.0-1
molecule-docker 2.0.0-1
```

molecule:
```
% molecule --version
molecule 4.0.0 using python 3.10
    ansible:2.13.2
    delegated:4.0.0 from molecule
    docker:2.0.0 from molecule_docker requiring collections: community.docker>=3.0.0-a2
    podman:2.0.0 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:1.0.0 from molecule_vagrant
```

Pip dependencies:

```
% pip freeze | grep ansible
ansible==6.1.0
ansible-compat==2.1.0
ansible-core==2.13.2
ansible-lint==6.3.0
```

Ansible galaxy collections:

```
% ansible-galaxy collection list
# /usr/lib/python3.10/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
------8<---------------

# /home/mk/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.2.0
community.docker  2.7.0
community.general 3.4.0
```

After installing it as per @hylaride's suggestion, it works fine.

Could it be that the `>=` version operator might not work with pre-releases (`-a2`)?

**Comment by mikedep333** [comment]
I'm running into a similar issue, not sure if it is related or not.

It only occurs on our ansible 2.9 tests, other versions are unaffected:

```
INFO    Running source-cluster > dependency
Molecule source-cluster > dependency
  INFO     Running ansible-galaxy collection install -v --force --pre community.docker:>=3.0.0-a2
  WARNING  Retrying execution failure 2 of: ansible-galaxy collection install -v --force --pre community.docker:>=3.0.0-a2
  ERROR    Command returned 2 code:
  
  Invalid -W option ignored: unknown warning category: 'CryptographyDeprecationWarning'
  usage: ansible-galaxy [-h][--version][-v] TYPE ...
  ansible-galaxy: error: unrecognized arguments: --pre
```

**Comment by ssbarnea** [comment]
We do not support any version of ansible before 2.12, do not try to use it with these.

In fact I quite surprised you reported that because AFAIK, molecule v4 will likely throw an error if you try to use it ansible-core before 2.12.

**Comment by ssbarnea** [comment]
Ansible-galaxy from old versions of ansible is **very buggy**, I would say crippled.
