### ISSUE TITLE
ModuleNotFoundError: No module named 'molecule_docker'

### ISSUE THREAD

**Issue by jkirk** [ansible-community/molecule-docker#91]
When using the latest molecule_docker release (1.0.0), molecule reports an "No module named 'molecule_docker'" error:

```
❯ cat requirements.txt 
ansible<2.10
ansible-lint
molecule[docker,lint]
yamllint

❯ python3 -m venv venv

❯ pip install pip setuptools wheel

❯ pip install -r requirements.txt

❯ molecule --version                                                 
Failed to load driver entry point Traceback (most recent call last):
  File "/home/jkirk/projects/misc/ansible-role-website/venv/lib/python3.9/site-packages/molecule/api.py", line 45, in drivers
    pm.load_setuptools_entrypoints("molecule.driver")
  File "/home/jkirk/projects/misc/ansible-role-website/venv/lib/python3.9/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'molecule_docker'

molecule 3.4.0 using python 3.9 
    ansible:2.9.25
    delegated:3.4.0 from molecule

❯ molecule init scenario -r ansible-role-website --driver-name docker
Failed to load driver entry point Traceback (most recent call last):
  File "/home/jkirk/projects/misc/ansible-role-website/venv/lib/python3.9/site-packages/molecule/api.py", line 45, in drivers
    pm.load_setuptools_entrypoints("molecule.driver")
  File "/home/jkirk/projects/misc/ansible-role-website/venv/lib/python3.9/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'molecule_docker'

Usage: molecule init scenario [OPTIONS] [SCENARIO_NAME]
Try 'molecule init scenario --help' for help.

Error: Invalid value for '--driver-name' / '-d': 'docker' is not 'delegated'.
```

This used to work fine with molecule_docker 0.2.4.

My current workaround is to avoid 1.0.0:
```
❯ cat requirements.txt
ansible<2.10
ansible-lint
molecule[docker,lint]
molecule_docker<1.0.0
yamllint
```

**Comment by bodsch** [comment]
The same here.
